--liquibase formatted sql

--changeset Andrei:1
create table client
(
    id   int GENERATED BY DEFAULT as identity PRIMARY KEY,
    name varchar(128),
    age  int
);

--changeset Andrei:2
create table book
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     varchar(128),
    year      int,
    client_id int references client (id) ON DELETE CASCADE
);

--changeset Andrei:3
insert into client(id, name, age)
values (1, 'Andrei', 28),
       (2, 'Ihar', 29),
       (3, 'Jorik', 30);
